Problem Statement : Hospital Patient Data Analysis

Context: A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.

Tasks:

1. Load the patient dataset and show summary with info().

2. Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

3. Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

4. Use groupby to find total bill amount per department.

5. Remove duplicate patient records based on PatientID.

6. Fill missing BillAmount values with the mean bill amount.

7. Merge the billing dataset with patient dataset on PatientID.

8. Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

9. Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

Expected Outcome:

· Final cleaned dataset with accurate billing info.

· All missing values handled, merged dataset across PatientID.

· Ability to perform further analytics on department-wise revenue or doctor performance.

In [1]:
import pandas as pd
df = pd.read_csv("Patient_Data.csv")
df1 = pd.read_csv("Billing_Data.csv")
df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [2]:
df1

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [3]:
df = df[['PatientID', 'Department', 'Doctor', 'BillAmount']]
print(df)

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [5]:
print(df.columns)

Index(['PatientID', 'Department', 'Doctor', 'BillAmount'], dtype='object')

In [10]:
df.isnull().sum()

PatientID     0
Department    0
Doctor        0
BillAmount    2
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PatientID   6 non-null      int64
 1   Department  6 non-null      object
 2   Doctor      6 non-null      object
 3   BillAmount  4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

In [12]:
department_total = df.groupby('Department')['BillAmount'].sum()

print(department_total)

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [13]:
df = df.drop_duplicates(subset='PatientID')
df

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

In [14]:
mean_value = df['BillAmount'].mean()

df['BillAmount'] = df['BillAmount'].fillna(mean_value)
df

C:\Users\gurra\AppData\Local\Temp\ipykernel_17636\1735519892.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BillAmount'] = df['BillAmount'].fillna(mean_value)

   PatientID   Department     Doctor   BillAmount
0        101   Cardiology  Dr. Smith  5000.000000
1        102    Neurology   Dr. John  6233.333333
2        103  Orthopedics    Dr. Lee  7500.000000
3        104   Cardiology  Dr. Smith  6200.000000
4        105  Dermatology   Dr. Rose  6233.333333

In [15]:
df.isnull().sum()

PatientID     0
Department    0
Doctor        0
BillAmount    0
dtype: int64

In [16]:
df1

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [17]:
df1.isnull().sum()

PatientID           0
InsuranceCovered    0
FinalAmount         0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PatientID   5 non-null      int64
 1   Department  5 non-null      object
 2   Doctor      5 non-null      object
 3   BillAmount  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 200.0+ bytes

In [19]:
MergedData = pd.merge(df,df1,on='PatientID')
print(MergedData.head())

   PatientID   Department     Doctor   BillAmount  InsuranceCovered  \
0        101   Cardiology  Dr. Smith  5000.000000              2000
1        102    Neurology   Dr. John  6233.333333              1500
2        103  Orthopedics    Dr. Lee  7500.000000              2500
3        104   Cardiology  Dr. Smith  6200.000000              3000
4        105  Dermatology   Dr. Rose  6233.333333              1000

   FinalAmount
0         3000
1         3500
2         5000
3         3200
4         4000

In [20]:
NewPatients = pd.DataFrame({'PatientID':[106,107],'Department':['Cardiology', 'Neurology'],'Doctor':['Dr.Ravi','Dr.Priya'],'BillAmount':[7000,8500]})
print(NewPatients)

   PatientID  Department    Doctor  BillAmount
0        106  Cardiology   Dr.Ravi        7000
1        107   Neurology  Dr.Priya        8500

In [35]:
MergedData = pd.concat([df,NewPatients],ignore_index=True)

print(MergedData)

   PatientID   Department     Doctor   BillAmount
0        101   Cardiology  Dr. Smith  5000.000000
1        102    Neurology   Dr. John  6233.333333
2        103  Orthopedics    Dr. Lee  7500.000000
3        104   Cardiology  Dr. Smith  6200.000000
4        105  Dermatology   Dr. Rose  6233.333333
5        106   Cardiology    Dr.Ravi  7000.000000
6        107    Neurology   Dr.Priya  8500.000000

In [38]:
NewBilling = pd.DataFrame({
    'InsuranceCovered':[1000,1500,1200,1800,2000,1000,1500],
    'FinalAmount':[4000,5500,5000,6200,6500,6000,7000]
})

FinalData = pd.concat([MergedData, NewBilling], axis=1)

print(FinalData)

   PatientID   Department     Doctor   BillAmount  InsuranceCovered  \
0        101   Cardiology  Dr. Smith  5000.000000              1000
1        102    Neurology   Dr. John  6233.333333              1500
2        103  Orthopedics    Dr. Lee  7500.000000              1200
3        104   Cardiology  Dr. Smith  6200.000000              1800
4        105  Dermatology   Dr. Rose  6233.333333              2000
5        106   Cardiology    Dr.Ravi  7000.000000              1000
6        107    Neurology   Dr.Priya  8500.000000              1500

   FinalAmount
0         4000
1         5500
2         5000
3         6200
4         6500
5         6000
6         7000

In [37]:
FinalData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         7 non-null      int64
 1   Department        7 non-null      object
 2   Doctor            7 non-null      object
 3   BillAmount        7 non-null      float64
 4   InsuranceCovered  7 non-null      int64
 5   FinalAmount       7 non-null      int64
dtypes: float64(1), int64(3), object(2)
memory usage: 468.0+ bytes